// <auto-generated />
using AutoPlacApp.Servisi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoPlacApp.Servisi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230818003059_spUzmiAuto")]
    partial class spUzmiAuto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoPlacApp.Modeli.Auto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Boja")
                        .HasColumnType("int");

                    b.Property<int>("BrojSedista")
                        .HasColumnType("int");

                    b.Property<int>("BrojVrata")
                        .HasColumnType("int");

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<int>("GodinaProizvodnje")
                        .HasColumnType("int");

                    b.Property<int>("Gorivo")
                        .HasColumnType("int");

                    b.Property<int>("Karoserija")
                        .HasColumnType("int");

                    b.Property<int>("Kilometraža")
                        .HasColumnType("int");

                    b.Property<int>("Klima")
                        .HasColumnType("int");

                    b.Property<int>("Kubikaža")
                        .HasColumnType("int");

                    b.Property<int>("Marka")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SlikaDir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SnagaMotora")
                        .HasColumnType("int");

                    b.Property<int>("Stanje")
                        .HasColumnType("int");

                    b.Property<int>("StranaVolana")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Automobili");
                });
#pragma warning restore 612, 618
        }
    }
}
